logFilters:
  - level: discard
    text: "load-grunt-config@npm:0.19.2 doesn't provide grunt (p9ff33), requested by jit-grunt"
  - level: discard
    text: "@joint/layout-directed-graph@workspace:packages/joint-layout-directed-graph provides rollup (p3b830) with version 4.9.0, which doesn't satisfy what rollup-plugin-uglify requests"

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
